name: CI Workflow

on:
  push:
    branches:
      - '**'  # Runs on all branches
    tags:
      - '*'   # Runs on tag pushes
  pull_request:
    branches:
      - main
      - develop

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install ruff
        run: |
          pip install uv
          sudo apt install just
          uv sync --extra lint

      - name: Lint code with ruff
        run: just lint
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync --dev

      - name: Install Just
        run: |
          sudo apt install just

      - name: Authenticate with GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS" | base64 -d > "${HOME}/gcloud-key.json" 2>/dev/null
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
          gcloud config set project ace-world-453411-e9
            
      - name: Run tests with pytest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          just test
        continue-on-error: true

      - name: Upload coverage results
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
        if: success()

  generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access to the repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if gh-pages exists
        id: check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Just
        run: |
          sudo apt install just

      - name: Install dependencies (uv and packages). Initialise environment
        run: |
          pip install uv
          just init-env

      - name: Build and render documentation with Quarto
        run: |
          uv run quarto render

      - name: Publish (Run only if gh-pages exists)
        if: env.exists == 'true' && github.ref_name != 'gh-pages'
        run: |
          uv run quarto publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Build package
        run: uv build

      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/